name: superformula_test
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  qr_flutter: ^4.0.0
  dio: ^4.0.6
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  get_it: ^7.2.0
  mobile_scanner: ^3.0.0
  mocktail: ^0.3.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/superformula.jpeg

 